### ISSUE TITLE
multiple arrays?

### ISSUE THREAD

**Issue by prushp** [01org/tinycbor#38]
Can I have multiple arrays at the same time?
For instance does the following sequence work?

cbor_encoder_create_map(&stream, &map, 2);

// Create first array.
cbor_encode_text_stringz(&map, "array1");
cbor_encoder_create_array(&map, &array1, CborIndefiniteLength);

// Create a second array.
cbor_encode_text_stringz(&map, "array2");
cbor_encoder_create_array(&map, &array2, CborIndefiniteLength);

cbor_encode_int(&array1, data1);
cbor_encode_int(&array2, data2);    // this overwrites array1.

Are there other ways to do this? Can you provide an example on how to manage two arrays within one cbor stream?

**Comment by thiagomacieira** [comment]
You cannot do that. TinyCBOR is not meant to be a DOM structure, so it will not hold the multiple values. It's a streaming encoder (StAX). You need to finish the first array before beginning the second.

If you need to manage two arrays at the same time, do so prior to encoding. If you want, I can add a feature so that you can write to two buffers in parallel, and then just copy what has already been encoded in one onto the other.

**Comment by prushp** [comment]
Thanks for the reply.

How about a cbor_encode_merge function()? It is essentially the same thing as you proposed. However this will be more generic. Sort of a strcat function; we can have two arrays managed separately in their own streams and can be merged later.
Let's assume stream 1  is open and stream  2 is closed, I would like to call something like
       cbor_encode_merge(stream1, stream2) 
which can copy the map from stream2 in to stream1's tail.
